### ISSUE TITLE
样例代码直接运行无法渲染出来

### ISSUE THREAD

**Issue by wondrahy** [zzz0908/vue3-resize-drag#1]
你好，我直接下载源码, npm install,  npm run serve之后，页面未正确渲染出来，也无错误提示，这是什么情况？
![image](https://user-images.githubusercontent.com/7781354/112843058-c6572b00-90d4-11eb-937e-7fc2e816fc98.png)

**Comment by zzz0908** [comment]
我写的demo未在插件中引入&nbsp; &nbsp;如果你想看的话需要修改vue.config.js中 entry配置项&nbsp; 我写着注释呢&nbsp; 把入口文件改为entry:&nbsp;'src/demo/main.ts'



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年3月29日(星期一) 晚上9:22
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; 
主题: [zzz0908/vue3-resize-drag] 样例代码直接运行无法渲染出来 (#1)





 
你好，我直接下载源码, npm install,  npm run serve之后，页面未正确渲染出来，也无错误提示，这是什么情况？

**Comment by wondrahy** [comment]
好的，非常感谢。







--

                         此致
 敬礼！！
 
                                                         王振海




在 2021-03-30 16:35:44，"zzz0908" ***@***.***> 写道：

我写的demo未在插件中引入&nbsp; &nbsp;如果你想看的话需要修改vue.config.js中 entry配置项&nbsp; 我写着注释呢&nbsp; 把入口文件改为entry:&nbsp;'src/demo/main.ts'



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;;
发送时间: 2021年3月29日(星期一) 晚上9:22
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [zzz0908/vue3-resize-drag] 样例代码直接运行无法渲染出来 (#1)






你好，我直接下载源码, npm install, npm run serve之后，页面未正确渲染出来，也无错误提示，这是什么情况？
